development:
  clients:
    default:
      uri: 'mongodb://heroku_wrffhs66:slrt5bta1c4vtc6a0kvejcfjeq@ds061354.mongolab.com:61354/heroku_wrffhs66'

test:
  clients:
    default:
      database: icare_test
      hosts:
        - localhost:27017

staging:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>

production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
